### ISSUE TITLE
thanks for your contribution

### ISSUE THREAD

**Issue by zhangchaoxu** [ourbeehive/MyBatisPoineer#1]
@siyueshiqi 
Thank u for your contribution to ourbeehive org.
Just focus on coding, I will help on document init and CI.

@ajoybee 老大，作为ourbeehive的发起人，你不能放弃这个项目啊。
[AndPlug](https://github.com/ourbeehive/AndPlug) has published two sub-modules in maven and jcenter.

**Comment by ajoybee** [comment]
不会的，呵呵。不久就会有让大家惊艳的东西。

2015-12-28 


---------------------------------------
赵瑞彬
Email：    iamzhaorb@126.com
Mobile： 13910028395
WeChat：RuiBinDeWeiXin



发件人：Charles Zhang <notifications@github.com>
发送时间：2015-12-28 15:40
主题：[MyBatisPoineer] thanks for your contribution (#1)
收件人："ourbeehive/MyBatisPoineer"<MyBatisPoineer@noreply.github.com>
抄送："ajoybee"<zhaorb@vip.sina.com>

@siyueshiqi 
Thanks u for your contribution to ourbeehive org.
Just focus on coding, I will help on document init and CI.
@ajoybee 老大，作为ourbeehive的发起人，你不能放弃这个项目啊。
AndPlug has published two sub-modules in maven and jcenter.

**Comment by zhangchaoxu** [comment]
好嘞
